### PR TITLE
Fix custom fields checkbox list

### PR DESCRIPTION
**Pull request by stanleylhs**
* Fix error when saving custom fields checkbox list (YAML serialization is not required on the form)
* Removed obselete "checkbox" field code in render method. This was legacy code.
* Added warning to restart Rails server as 'Checkbox list' custom field serialization must apply to all instances of Rails (eager load issue).

image

### CODE REVIEW

**Review by CloCkWeRX — CHANGES_REQUESTED** [review]
Failing tests

**Comment by steveyken** [comment]
I'm happy to dig into this in a couple of weeks time.

**Comment by steveyken** [comment]
I've re-written the failing specs to ensure this is working properly.

**Review by steveyken — APPROVED** [review]
I've improved the specs and tested the changes locally. This will fix the checkbox list form rendering

**Pull request merged**
