### PR TITLE
Drop ruby 2.3 for 2.5 support

### PR DESCRIPTION
**Pull request by CloCkWeRX**
#659 

Ruby 2.2 
status: security maintenance
release date: 2014-12-25
EOL date: scheduled for 2018-03-31

so this is probably mergable 2019-03-31

### CODE REVIEW

**Comment by johnnyshields** [comment]
We should add Ruby 2.5 and continue running on Ruby 2.3 until it actually goes EOL. We don't need to have PR open until then.

**Comment by johnnyshields** [comment]
Hmmm I'm ok with dropping Ruby 2.3 actually.

**Comment by CloCkWeRX** [comment]
Blocked by https://github.com/travis-ci/travis-ci/issues/8978
```LoadError: cannot load such file -- bundler/dep_proxy```

**Comment by CloCkWeRX** [comment]
Neat, that should pass in a few minutes, requeued the one failed bit under 2.5.0.

I think we can safely drop testing under 2.3.0 (saving ~7 minutes of execution time); but we just keep the >= 2.3.0 in the gemspec and target version: 2.3 in rubocop to make sure we don't add new language features that probably wont run.

**Comment by CloCkWeRX** [comment]
Doh, merged that wrong.

**Comment by CloCkWeRX** [comment]
Oops, we merged this a bit early so its in the 0.17.0 release (we jumped 2x ruby versions).

I might revert this and cut 0.17.1

**Pull request merged**
