### PR TITLE
Chilean spanish lang

### PR DESCRIPTION
**Pull request by dalacost**
improvement from spanish lang, including chilean currency and new keys.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://dalacost-patch-2.fatfreecrm-fat-free-crm-1bbda9a74e1b4e1e2ffd.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://dalacost-patch-2.fatfreecrm-fat-free-crm-1bbda9a74e1b4e1e2ffd.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by stanleylhs** [comment]
👍

**Comment by steveyken** [comment]
Thank you!

**Comment by dalacost** [comment]
Thank to you for add me changes!

**Pull request merged**
