### PR TITLE
Update libv8 gem version from 3.16.14.13 to 3.16.14.15

### PR DESCRIPTION
**Pull request by papilip**
Hello, for install in freebsd, i must update libv8 to 3.16.14.15

### CODE REVIEW

**Comment by devcurmudgeon** [comment]
this also is required for MacOS now... please merge

**Comment by CloCkWeRX** [comment]
Fixes #503

**Comment by devcurmudgeon** [comment]
Thanks!

**Comment by CloCkWeRX** [comment]
I have no write access, though I've suggested it should be shared around a bit in #529.

That will probably work itself out, but worst case we do a friendly fork of it.

**Comment by CloCkWeRX** [comment]
I did a different version of this in ea0ac6333bdd93ee95b99e1a957b6116b8d4f248 on the fork of ffcrm

**Comment by CloCkWeRX** [comment]
I merged the above commit to https://github.com/reduced-fat-crm/fat_free_crm and it should be present in https://rubygems.org/gems/reduced_fat_crm/versions/0.14.0 - did you want to see if that works?

**Comment by CloCkWeRX** [comment]
Closing now that ea0ac63  is merged

**Pull request closed without merging**
