### PR TITLE
Fix smtp host

### LINKED ISSUE #590: host takes presedence over from in SMTP config, breaking relay
__Steps to reproduce__:

1. Configure host in `config/settings.yml`:

    ```yaml
    :host: "subdomain.domain.com"
    ```

2. Configure smtp in `config/settings.yml`:

    ```yaml
    :smtp:
      :address: "smtp.sparkpostmail.com"
      :port: 587
      :from: "no-reply@domain.com"
      :enable_starttls_auto: true
      :authentication: :plain
      :user_name: "SMTP_Injection"
      :password: "<password>"
    ```
3. Add Note under different user accounts to trigger email

__What happens__: email that is relayed is constructed with `host` setting, e.g. 

```
From: "<user>" <no-reply@subdomain.domain.com>
```

causing DKIM check for verified senders to fail on SparkPost (or any other external service).

__What should happen__: Email should be relayed as by SMTP configuration, with 

```
From: "<user>" <no-reply@domain.com>
```

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Fixes #590 

@ain can you try this one out and see if it fixes the issue

### CODE REVIEW

**Comment by ain** [comment]
I'll pull and test over the weekend. Had the same idea about aligning these 2 yesterday. 

Thanks for the work!

**Comment by ain** [comment]
@CloCkWeRX tested, works!

**Comment by CloCkWeRX** [comment]
I keep meaning to go work out what the specs are trying to do; and getting distracted. If you wanted to have a crack at it, more than welcome to steal this PR.

**Comment by ain** [comment]
@CloCkWeRX I was already setting it up, but as I run all my stacks on Docker currently, I ran into several problems there. I think the whole Docker setup is outdated and needs to be rethought. I'm into that currently.

**Comment by CloCkWeRX** [comment]
Replacing this with #657

**Pull request closed without merging**
