### PR TITLE
Fix #413 Profile phone number not html_safe

### LINKED ISSUE #413: Profile phone number not html_safe
Phone number in profile isn't `html_safe`:

phone_no_html_safe_issue

### PR DESCRIPTION
**Pull request by ain**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://ain-fix-413-profile-phone-number.fatfreecrm-fat-free-crm-1bbda9a74e1b4e1e2ffd.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://ain-fix-413-profile-phone-number.fatfreecrm-fat-free-crm-1bbda9a74e1b4e1e2ffd.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by steveyken** [comment]
Thanks, taking a look at this, I think a better approach would be to use the content_tag helper to wrap  safe <b> tags around the phone number ... I think the change above actually makes it possible for any javascript in the phone number to be executed the browser.

The safe approach would be

    content_tag(:b, user.phone_number)

**Comment by steveyken** [comment]
Which url view did this appear on? Was it /admin/users? Thanks.

**Comment by ain** [comment]
@steveyken `/profile`.

**Comment by steveyken** [comment]
Fixed by https://github.com/fatfreecrm/fat_free_crm/commit/ff36f365cf95166170c5fee36509f71fe71064fc

**Pull request closed without merging**
