### PR TITLE
Release 0.17.0

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Updated the changelogs, but let's talk through anything else that we really need to document.

https://github.com/fatfreecrm/fat_free_crm/milestone/5

- [x] Is #685 a blocker
- [x] ~~Is #694 a blocker~~
- [x] ~~Do we need to document anything for the chozen -> select2 migration (plugins, people using FFCRM as an engine?)~~ Committed note to this PR.
- [x] ~~Anything else?~~ Nothing comes to mind.

### CODE REVIEW

**Comment by johnnyshields** [comment]
@CloCkWeRX We should fix points 1-3 before release.

@DmitryAvramec can you help with these?

**Comment by johnnyshields** [comment]
#707 adds not about Chozen to readme.

**Comment by johnnyshields** [comment]
@CloCkWeRX please confirm #685 (merged) locally then we're good to release.

**Comment by CloCkWeRX** [comment]
Seems to be working, but is pretty slow with 100,000 records or so!

**Comment by CloCkWeRX** [comment]
Migrations still running. Tempting to pull update-counter-caches to a one off rake task

**Pull request merged**
