### PR TITLE
Fix oppportunities sort by weighted amount

### PR DESCRIPTION
**Pull request by DmitryAvramec**
In case you select sort opportunities by weghted amount, you got an error. So this fix let us sort it, but dont think it's ok solution.

### CODE REVIEW

**Comment by johnnyshields** [comment]
Can you provide more details of why the error happens?

**Comment by DmitryAvramec** [comment]
We have this error:
image
Here we have almost same problem: 
https://github.com/rails/rails/issues/31783
Seems like PostgreSQL dont like SELECT DISTINCT statement with ORDER BY.

**Comment by CloCkWeRX** [comment]
This can be worked around by doing queries like:
```
.select('amount * probability, opportunities.*').order('amount * probability')
```

**Comment by johnnyshields** [comment]
@DmitryAvramec can you try @CloCkWeRX 's solution here?

**Comment by DmitryAvramec** [comment]
@CloCkWeRX look at this solution.

**Pull request merged**
