### PR TITLE
Language pt-BR update

### PR DESCRIPTION
**Pull request by johnmarques**
I made some updates to the pt-BR language file

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://johnmarques-master.fatfreecrm-fat-free-crm-1bbda9a74e1b4e1e2ffd.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://johnmarques-master.fatfreecrm-fat-free-crm-1bbda9a74e1b4e1e2ffd.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by johnmarques** [comment]
One could perform the merge?

**Comment by steveyken** [comment]
Thanks very much. I'll merge shortly when I can spend a bit of time focussing on PR's.

**Comment by johnmarques** [comment]
Ok Stevey thank you

**Pull request merged**
