### PR TITLE
Translating to Dutch

### PR DESCRIPTION
**Pull request by davidakachaos**
Added translations for Dutch.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://davidakachaos-translate-nl.fatfreecrm-fat-free-crm-1bbda9a74e1b4e1e2ffd.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://davidakachaos-translate-nl.fatfreecrm-fat-free-crm-1bbda9a74e1b4e1e2ffd.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by steveyken** [comment]
Hi @davidakachaos thank you for this. Travis is reporting some test failures above but I believe they are not related to the translation work you've done. We'll correct those separately and then bring this in. Thank you for your contribution.

**Comment by davidakachaos** [comment]
@steveyken ping? :smile:

**Comment by stanleylhs** [comment]
@davidakachaos I rebased you commits to the latest master but I can't boot it up!

I18n::MissingTranslationData in Home#index
fat_free_crm/app/views/home/_task.html.haml where line #29 raised:

translation missing: nl.time.formats.mmddhhss

**Comment by steveyken** [comment]
Done. Thank you for your patience!

**Comment by stanleylhs** [comment]
👍

**Pull request merged**
