### PR TITLE
Safe navigation

### LINKED ISSUE #647: Adopt min ruby version of 2.3.0 and apply safe navigiation rubocop rules

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Fix #647

### CODE REVIEW

**Comment by johnnyshields** [comment]
0.17.0

**Comment by johnnyshields** [comment]
```
Offenses:
app/controllers/admin/application_controller.rb:25:8: C: Use safe navigation (&.) instead of checking if an object exists before calling the method.
    if current_user && !current_user.admin?
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app/helpers/application_helper.rb:162:8: C: Use safe navigation (&.) instead of checking if an object exists before calling the method.
    if Setting.email_dropbox && Setting.email_dropbox[:address].present?
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app/models/observers/lead_observer.rb:17:8: C: Use safe navigation (&.) instead of checking if an object exists before calling the method.
    if original && original.status != "rejected" && item.status == "rejected"
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by CloCkWeRX** [comment]
Interesting: https://github.com/bbatsov/rubocop/issues/5392

**Comment by CloCkWeRX** [comment]
I might do #655 first

**Pull request merged**
