### PR TITLE
Fix for #1122 - working under WSL2, Ruby 3.0.6

### PR DESCRIPTION
**Pull request by ferrisoxide**
Various small fixes to get FatFreeCRM installing under WSL using Postgres and Ruby 3.0.6

NB Updating Ruby appears necessary - at least on WSL - to get `mini_racer` to install. It assumes use of the geckodriver for executing feature specs via modern Firefox.

This also attempts to fix https://github.com/fatfreecrm/fat_free_crm/issues/1122

This is my first PR for FatFreeCRM, so I'm not sure if pushing an update to the Ruby version, etc is compatible with what the community is after.

### CODE REVIEW

**Comment by ferrisoxide** [comment]
Hi folks.

The PR is working for me locally now, so I've removed the "WIP".  This is my first PR for FatFreeCRM, so I'm not sure if pushing an update to Ruby, etc is compatible with what the community is after.

**Comment by nelsonmatenda** [comment]
it worked...

**Comment by CloCkWeRX** [comment]
Basically the standard for if a PR is worth it is if it's fixing a problem :)

I would maybe suggest splitting upgrades vs other issues, maybe using an issue to track the big picture.

But, let me take a bit of a look

**Comment by ferrisoxide** [comment]
> I would maybe suggest splitting upgrades vs other issues, maybe using an issue to track the big picture.

OK, I'll look at splitting these into separate PRs. K++

**Comment by ferrisoxide** [comment]
Closing this PR in favour of separate issue-specific PRs. See

* #1137
* #1139

**Pull request closed without merging**
