### PR TITLE
Fix #563 invalid default custom field minlength

### LINKED ISSUE #563: custom_field: text-input fields min_length set to maximum by default
min_length is set to 255 or 64k for text-area by default and cannot be overridden.

```<textarea rows="7" class="text optional" maxlength="65535" minlength="65535" placeholder="xxxx" name="account[cf_test]" id="account_cf_test"></textarea>```

### PR DESCRIPTION
**Pull request by ain**

### CODE REVIEW

**Comment by ain** [comment]
I am not understanding the logic behind `db/schema.rb` validation. It has been automatically generated by Rails itself when using `mysql2`. Please advise.

**Comment by ain** [comment]
@CloCkWeRX care to take a look into this? I switched the database to postgres, but I'm still getting the following:

```
Offenses:
db/schema.rb:15:1: C: Extra empty line detected at block body beginning.
db/schema.rb:460:1: C: Extra empty line detected at block body end.
```

It really doesn't make much sense since the schema is autogenerated. I'm using `posgres:9.5` here.

**Comment by johnnyshields** [comment]
@CloCkWeRX I'll own this one after we merge the current outstanding PRs.

**Comment by johnnyshields** [comment]
Replaced by #670

**Pull request closed without merging**
