### PR TITLE
Rails 7

### LINKED ISSUE #1134: Error loading page: DEPRECATION WARNING: Initialization autoloaded the constant Setting.
Hey all, I'm getting an error when trying to load a page after booting the app that a constant object was auto loaded on initialisation. See below for a screenshot of the logs showing that error:

alt

All I've done with the app is following the setup instructions (bundle install, db:setup, etc) but I'm not sure why I seem to be the only one experiencing this issue? I'm on an Macbook Pro (M2 Pro chip) if that changes anything? Seems to be related to calling model classes within the `/lib` or `/config` directory

### PR DESCRIPTION
**Pull request by romanbsd**
Here's another take on upgrade to Rails 7. I tried my best to merge the configuration by hand while preserving the copyrights and custom configuration. I believe that as soon as acts_as_commentable supports Rails 7.1, fat_free_crm will support it as well. All tests passed locally.

Fixes #1134

### CODE REVIEW

**Comment by johnbumgardner** [comment]
Hey I approved CI builds for this PR. Please fix the testing and I'd be happy to approve. Thanks for the help!

**Comment by romanbsd** [comment]
ok. Fixed. That was something peculiar with the way sqlite3 adapter was handling the id: :serial. It didn't produce the proper autoincrement field on SQLite.

**Comment by romanbsd** [comment]
Good to go?

**Comment by CloCkWeRX** [comment]
Thanks! I think this is pretty much good to go with the green build.

I will have to think slightly about the fork of acts_as_commentable - I'd done my own as a quick and dirty fix; and it's a bit unmaintained. Might merge your fork + my fork together, make a feature branch, stick in the fat free crm organisation.

**Pull request merged**
