### PR TITLE
Fix for Multiword Tags

### PR DESCRIPTION
**Pull request by johnbumgardner**
Allow support to search for a multiword tag by surrounding the tag with # #

image

image

### CODE REVIEW

**Comment by johnnyshields** [comment]
@johnbumgardner possible to add a test for this?

**Comment by johnbumgardner** [comment]
@johnnyshields just wrote and pushed it

**Comment by johnnyshields** [comment]
Merged, thanks for the contribution!

**Comment by johnbumgardner** [comment]
@johnnyshields are they any other issues you can suggest that i can help with?

**Comment by johnnyshields** [comment]
@johnbumgardner I'm not really actively involved with this project much more. Was thinking to do a major upgrade at some point but no bandwidth currently. That being said would certainly appreciate PRs if you encounter anything during your usage that needs to be added or fixed,

**Pull request merged**
