### PR TITLE
Made engine advertise factories for future usage in parent app

### PR DESCRIPTION
**Pull request by DmitriySalko**
When used as an engine, it's good to expose engine's factories so they can be used in rails app tests.

More here:
https://github.com/cryo28/factory_girl_rails/commit/191ce5e47e495d2dd7a6b7a8247163e4200cc364

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://dmitriysalko-expose-factories.fatfreecrm-fat-free-crm-1bbda9a74e1b4e1e2ffd.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://dmitriysalko-expose-factories.fatfreecrm-fat-free-crm-1bbda9a74e1b4e1e2ffd.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by steveyken** [comment]
Great, I've been wanting this feature for a while so I can use it to test plugins without needing to copy factories over. Will give it a try and merge. Thanks for the code.

**Comment by steveyken** [comment]
I've merged this commit. Can you provide a sample of how you might use the factories in a plugin? Many thanks.

**Comment by DmitriySalko** [comment]
Sure. I'll do it next week.

**Comment by DmitriySalko** [comment]
Here is an example rails app ( should also work for plugins ).

https://github.com/DmitriySalko/ffcrm_factories_demo

Here https://github.com/DmitriySalko/ffcrm_factories_demo/blob/master/spec/support/features/sign_in.rb

I use ```user``` factory to login during feature test. Usually can be used for more complex scenarios like testing models, etc. Hope this helps.

**Comment by steveyken** [comment]
Thanks, this helped. Note to self: I discovered I needed to include ```factory_girl_rails``` in my plugin Gemfile and also load my extra factories in ```plugin_dir/spec/factories``` manually but otherwise, this works great.

**Pull request merged**
