### PR TITLE
Bugfix: Fix emails and add spec

### PR DESCRIPTION
**Pull request by johnnyshields**
This PR fixes something that broke during the Rails 5.1 upgrade

### CODE REVIEW

**Comment by johnnyshields** [comment]
@CloCkWeRX this should be merged before 0.16.0 release

**Comment by CloCkWeRX** [comment]
Ah, 0.16.0 is out already. Can easily cut a 0.16.1 release or push it to 0.17.0

**Comment by CloCkWeRX** [comment]
[36mapp/models/polymorphic/email.rb[0m:50:15: [33mC[0m: Use [33mtr[0m instead of [33mgsub[0m.
    body.to_s.gsub("\n", " ")
              ^^^^^^^^^^^^^^^

**Comment by johnnyshields** [comment]
0.16.1 would be best just in case.

**Comment by johnnyshields** [comment]
@CloCkWeRX ready to merge and release

**Pull request merged**
