### PR TITLE
Add Decorator Pattern to engine

### PR DESCRIPTION
**Pull request by adisos**
http://guides.rubyonrails.org/engines.html#overriding-models-and-controllers

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://spalmalo-master.fatfreecrm-fat-free-crm-1bbda9a74e1b4e1e2ffd.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://spalmalo-master.fatfreecrm-fat-free-crm-1bbda9a74e1b4e1e2ffd.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by CloCkWeRX** [comment]
As per above, I've added this into my fork, should be in the 0.14.0 release I think.

**Comment by adisos** [comment]
https://github.com/fatfreecrm/fat_free_crm/commit/90483230d63995b45848ed7a37fccc749cc87c30#diff-f000da26081f7ea2cf7efc6fe9a6ffe8

**Comment by adisos** [comment]
https://github.com/fatfreecrm/fat_free_crm/commit/90483230d63995b45848ed7a37fccc749cc87c30

**Pull request closed without merging**
